version: '3'
services:
  elementum:
    image: elementum
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ELEMENTUM_VERSION: ${ELEMENTUM_VERSION}
        ELEMENTUM_ARCH: ${ELEMENTUM_ARCH}
    environment:
      - "TZ=${TZ}"
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ${DOWNLOADS_DIR}:/storage/emulated/0/Download
    command:
      - elementum
      - -localHost=${LOCAL_IP}
      - -remoteHost=${REMOTE_IP}
    restart: unless-stopped
